root: true
extends:
  # rules
  - stylelint-config-standard
  # rules
  - stylelint-config-recommended
  # overrides: html
  - stylelint-config-html/html
  # overrides: vue
  - stylelint-config-recommended-vue
  # prettier
  # - stylelint-config-prettier
overrides:
  - files:
      - "*.less"
      - "**/*.less"
    customSyntax: postcss-less
    extends:
      - stylelint-config-standard
      - stylelint-config-recommended-vue
